#!/usr/bin/env python3
"""
backup_preimages.py — nightly PRIVATE off-machine backup of the
SoulPredictionOracle preimages (the rows behind each on-chain weekly Merkle
root). Without this, if the Mini's disk dies the on-chain roots survive but
become UNVERIFIABLE — inverting the whole "verify, don't trust" claim.

Writes into the PRIVATE repo clone ~/Documents/undesirables-oracle-preimages/
and commits+pushes ONLY when something changed:
  - soul_predictions.sqlite            (the whole 0.4MB DB — trivial to keep)
  - weeks/<weekId>.json                (per committed week: exact preimage rows +
                                        merkle root + on-chain tx + the leaf/tree
                                        recipe → each week self-verifies standalone)
  - README.md                          (how to reconstruct + verify)

NEVER public: contains paid-tier forecast values (prob_up/conf/price). The repo
is private; this script only pushes there.

Cron: nightly (after the Monday lock's data is in). Idempotent — re-running with
no new committed week is a no-op push.
"""
import os, json, shutil, sqlite3, subprocess, hashlib

X = os.path.expanduser("~/Documents/undesirables-x402-server")
DB = os.path.join(X, "soul_predictions.sqlite")
REPO = os.path.expanduser("~/Documents/undesirables-oracle-preimages")
CONTRACT = "0x5503D08D7D167eE23AcE818bff1a00eF77A76dBF"

README = """# SoulPredictionOracle — Preimage Backup (PRIVATE)

Off-machine backup of the exact rows behind every on-chain weekly Merkle root
committed to the **SoulPredictionOracle** (`%s`, LiteForge chain 4441). This is
what lets anyone RECONSTRUCT and VERIFY each root — the trust anchor for the
public soul track records. **Never make this repo public** (rows include
paid-tier forecast values).

## Files
- `soul_predictions.sqlite` — full source DB (soul_predictions + merkle_roots).
- `weeks/<weekId>.json` — one file per committed week, self-contained: every
  prediction's preimage row, the Merkle root, the on-chain tx, and the exact
  leaf + tree recipe used that week.

## How to verify a week's on-chain root
1. Open `weeks/<weekId>.json`. Rebuild each leaf from its row using `leaf_recipe`.
2. Build the Merkle tree using `tree_convention`, get the root.
3. Confirm it equals `merkle_root`, and that `merkle_root` matches what the
   contract stores at `commitments(weekId)` (or the calldata of `tx_hash`).
Match ⇒ the on-chain commitment provably corresponds to exactly these
predictions, locked before their 30-day outcomes existed.

## Leaf/tree conventions
- **Week 1 (20260701, legacy):** leaf = the row's `lock_hash` (sha256 of
  `token_id|as_of|product_id|direction|prob_up|conf|price`); tree = sorted hex
  leaves, sha256(concat) pairwise, duplicate-last-odd.
- **Week 2+ (OZ):** leaf = keccak256(keccak256(abi.encode(uint256 token_id,
  uint256 weekId, uint256 product_id, string direction, bytes32 lockHash)));
  tree = zero-pad to power of two, sorted-pair keccak256 internal nodes
  (OpenZeppelin MerkleProof convention).

_Auto-generated by scripts/backup_preimages.py. Do not edit by hand._
""" % CONTRACT


def main():
    if not os.path.isdir(REPO):
        raise SystemExit(f"preimages repo clone not found at {REPO}")
    os.makedirs(os.path.join(REPO, "weeks"), exist_ok=True)

    # 1) copy the whole DB (0.4MB — cheapest possible full backup)
    shutil.copy2(DB, os.path.join(REPO, "soul_predictions.sqlite"))

    # 2) per committed week: self-contained verification bundle
    c = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    weeks = c.execute("SELECT as_of, root, n_leaves, tx_hash FROM merkle_roots ORDER BY as_of").fetchall()
    for as_of, root, n, tx in weeks:
        week_id = int(as_of.replace("-", ""))
        rows = c.execute(
            "SELECT token_id, as_of, product_id, name, direction, prob_up_at_lock, conf, "
            "price_at_lock, matures_on, lock_hash FROM soul_predictions WHERE as_of=? "
            "ORDER BY token_id, product_id", (as_of,)).fetchall()
        legacy = (week_id == 20260701)
        bundle = {
            "weekId": week_id, "as_of": as_of,
            "contract": CONTRACT, "chain": "LiteForge (Caldera) chainId 4441",
            "merkle_root": root, "n_leaves": n, "tx_hash": tx,
            "tree_convention": ("legacy: sorted hex leaves, sha256(concat) pairwise, "
                                "duplicate-last-odd" if legacy else
                                "OZ: zero-pad to power-of-two, sorted-pair keccak256"),
            "leaf_recipe": ("leaf = the row's lock_hash (already the committed leaf)" if legacy else
                            "leaf = keccak256(keccak256(abi.encode(uint256 token_id, uint256 weekId, "
                            "uint256 product_id, string direction, bytes32 lockHash)))"),
            "lock_hash_preimage": "sha256('token_id|as_of|product_id|direction|prob_up|conf|price')",
            "predictions": [
                {"token_id": r[0], "as_of": r[1], "product_id": r[2], "name": r[3],
                 "direction": r[4], "prob_up": r[5], "conf": r[6], "price": r[7],
                 "matures_on": r[8], "lock_hash": r[9]} for r in rows],
        }
        # integrity self-check: rebuild each legacy lock_hash from its preimage
        if legacy:
            for p in bundle["predictions"]:
                canon = f"{p['token_id']}|{p['as_of']}|{p['product_id']}|{p['direction']}|{p['prob_up']}|{p['conf']}|{p['price']}"
                if hashlib.sha256(canon.encode()).hexdigest() != p["lock_hash"]:
                    bundle.setdefault("_warnings", []).append(f"lock_hash mismatch tok {p['token_id']} pid {p['product_id']}")
        with open(os.path.join(REPO, "weeks", f"{week_id}.json"), "w") as f:
            json.dump(bundle, f, ensure_ascii=False, indent=1)
    c.close()

    with open(os.path.join(REPO, "README.md"), "w") as f:
        f.write(README)

    # 3) commit + push, then VERIFY the remote actually received it. Loud +
    # phone-alert on any failure — a silent push failure (Jul 8-11: cron had no
    # headless git creds) left the disk-death insurance un-mirrored for 3 days.
    def git(*a):
        return subprocess.run(["git", "-C", REPO, *a], capture_output=True, text=True)

    def alert(msg):
        print(f"[backup] ❌ {msg}")
        topic = os.environ.get("NTFY_TOPIC")
        if not topic:
            for line in open(os.path.join(X, ".env")):
                if line.startswith("NTFY_TOPIC="):
                    topic = line.split("=", 1)[1].strip().strip('"').strip("'")
        if topic:
            try:
                import urllib.request
                urllib.request.urlopen(urllib.request.Request(
                    f"https://ntfy.sh/{topic}", data=f"PREIMAGE BACKUP FAILED: {msg}".encode(),
                    headers={"Title": "Undesirables preimage backup", "Priority": "high", "Tags": "warning"}),
                    timeout=15)
            except Exception as e:
                print(f"[backup] (ntfy alert also failed: {e})")

    git("add", "-A")
    if git("diff", "--cached", "--quiet").returncode != 0:      # staged changes present
        git("commit", "-q", "-m", f"preimage backup: {len(weeks)} committed week(s), {len(weeks)} roots")
    p = git("push", "origin", "HEAD:main")
    if p.returncode != 0:
        alert(f"git push failed: {(p.stderr or p.stdout).strip().splitlines()[-1][:120] if (p.stderr or p.stdout).strip() else 'unknown'}")
        raise SystemExit(1)
    # VERIFY off-machine: local HEAD must equal origin/main (proves the push landed)
    git("fetch", "origin", "-q")
    local = git("rev-parse", "HEAD").stdout.strip()
    remote = git("rev-parse", "origin/main").stdout.strip()
    if local != remote:
        alert(f"pushed but remote != local (HEAD {local[:8]} vs origin {remote[:8]}) — backup NOT off-machine")
        raise SystemExit(1)
    print(f"[backup] ✓ off-machine confirmed — weeks {[w[0] for w in weeks]}, remote @ {remote[:8]}")


if __name__ == "__main__":
    main()
